### ISSUE TITLE
Error when deleting linked annotation

### ISSUE THREAD

**Issue by JeannedArk** [annefried/discanno#158]
angular.js:12722 TypeError: Cannot read property 'startLine' of undefined
    at r.$scope.isVisible (http://localhost:8080/discanno/directives/d3Annotation.js:1760:57)
    at http://localhost:8080/discanno/directives/d3Annotation.js:1316:59
    at Array.filter (native)
    at r.$scope.drawLinks (http://localhost:8080/discanno/directives/d3Annotation.js:1311:70)
    at Object.fn (http://localhost:8080/discanno/directives/d3Annotation.js:448:36)
    at r.$digest (http://localhost:8080/discanno/bower_components/angular/angular.min.js:131:291)
    at r.$apply (http://localhost:8080/discanno/bower_components/angular/angular.min.js:134:236)
    at HTMLButtonElement.<anonymous> (http://localhost:8080/discanno/directives/d3Options.js:109:52)
    at HTMLButtonElement.__onclick (http://localhost:8080/discanno/bower_components/d3/d3.js:1120:18)

**Comment by JeannedArk** [comment]
Pull request: https://github.com/annefried/discanno/pull/192
