### ISSUE TITLE
Deselecting an annotations label leads to error

### ISSUE THREAD

**Issue by JeannedArk** [annefried/discanno#182]
TypeError: Cannot read property 'tag' of undefined
    at getColor (http://localhost:8080/discanno/controllers/annotationController.js:730:67)
    at setSelectedLabel (http://localhost:8080/discanno/controllers/annotationController.js:253:52)
    at fn (eval at <anonymous> (http://localhost:8080/discanno/bower_components/angular/angular.min.js:1:0), <anonymous>:4:401)
    at r.d.(anonymous function) [as setLabel](http://localhost:8080/discanno/bower_components/angular/angular.min.js:75:33)
    at http://localhost:8080/discanno/directives/d3Options.js:345:48
    at r.$eval (http://localhost:8080/discanno/bower_components/angular/angular.min.js:133:446)
    at r.$apply (http://localhost:8080/discanno/bower_components/angular/angular.min.js:134:175)
    at HTMLButtonElement.<anonymous> (http://localhost:8080/discanno/directives/d3Options.js:344:44)
    at HTMLButtonElement.__onclick (http://localhost:8080/discanno/bower_components/d3/d3.js:1120:18)

**Comment by JeannedArk** [comment]
Pull request: https://github.com/annefried/discanno/pull/191
