### ISSUE TITLE
Console Logging

### ISSUE THREAD

**Issue by JeannedArk** [annefried/discanno#38]
When using chrome, tick "preserve log" and some unnecessary stuff is logged and some errors while logging out/ in:
1
SyntaxError: Unexpected token L
    at Object.parse (native)
    at vc (http://localhost:8080/discanno/bower_components/angular/angular.min.js:15:483)
    at ac (http://localhost:8080/discanno/bower_components/angular/angular.min.js:82:360)
    at http://localhost:8080/discanno/bower_components/angular/angular.min.js:83:274
    at n (http://localhost:8080/discanno/bower_components/angular/angular.min.js:7:355)
    at ed (http://localhost:8080/discanno/bower_components/angular/angular.min.js:83:256)
    at c (http://localhost:8080/discanno/bower_components/angular/angular.min.js:84:468)
    at http://localhost:8080/discanno/bower_components/angular/angular.min.js:119:221
    at r.$eval (http://localhost:8080/discanno/bower_components/angular/angular.min.js:133:446)
    at r.$digest (http://localhost:8080/discanno/bower_components/angular/angular.min.js:131:41)(anonymous function) @ angular.js:12722(anonymous function) @ angular.js:9490(anonymous function) @ angular.js:14999r.$eval @ angular.js:16251r.$digest @ angular.js:16069r.$apply @ angular.js:16359g @ angular.js:10791R @ angular.js:10989v.onload @ angular.js:10930
Navigated to http://localhost:8080/discanno/signin.html

**Comment by JeannedArk** [comment]
When deleting an annotation belonging to a link
angular.js:12722 TypeError: Cannot read property 'startLine' of undefined
    at r.$scope.isVisible (http://localhost:8080/discanno/directives/d3Annotation.js:1779:57)
    at http://localhost:8080/discanno/directives/d3Annotation.js:1335:59
    at Array.filter (native)
    at r.$scope.drawLinks (http://localhost:8080/discanno/directives/d3Annotation.js:1330:70)
    at Object.fn (http://localhost:8080/discanno/directives/d3Annotation.js:447:36)
    at r.$digest (http://localhost:8080/discanno/bower_components/angular/angular.min.js:131:291)
    at r.$apply (http://localhost:8080/discanno/bower_components/angular/angular.min.js:134:236)
    at HTMLButtonElement.<anonymous> (http://localhost:8080/discanno/directives/d3Options.js:109:52)
    at HTMLButtonElement.__onclick (http://localhost:8080/discanno/bower_components/d3/d3.js:1120:18)

**Comment by JeannedArk** [comment]
When creating temporal annotation:
angular.js:12722 TypeError: Cannot read property 'tag' of undefined
    at SVGTitleElement.<anonymous> (d3Annotation.js:1209)
    at SVGTitleElement.arguments.length.each.value.function.value.textContent (d3.js:782)
    at d3.js:962
    at d3_selection_each (d3.js:968)
    at Array.d3_selectionPrototype.each (d3.js:961)
    at Array.d3_selectionPrototype.text (d3.js:781)
    at r.link.$scope.drawAnnotations (d3Annotation.js:1201)
    at Object.fn (d3Annotation.js:485)
    at r.$digest (angular.js:16095)
    at r.$apply (angular.js:16359)

This one is fixed now :white_check_mark:
